<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Jellyfin.Plugin.SmartBranching</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.SmartBranching</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <AnalysisMode>None</AnalysisMode>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>SmartBranching.Plugin.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.9.11">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.9.11">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Naming" Version="10.9.11">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Assets\Scripts\BVFReader.cs" Link="BVFReader.cs" />
    <Compile Include="..\Assets\Scripts\BVFSegment.cs" Link="BVFSegment.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html">
      <LogicalName>Jellyfin.Plugin.SmartBranching.Configuration.configPage.html</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
